# Generated by Django 4.2.7 on 2023-11-21 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]
    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.CharField(verbose_name='Rank')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(max_length=50, verbose_name='Названиетупа')),
                ('Name', models.CharField(max_length=50, verbose_name='Названиетупа')),
                ('Middlename', models.CharField(max_length=50, verbose_name='Названиетупа')),
                ('Employed', models.DateField(verbose_name='Date')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task.rank')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]

