# Generated by Django 4.2.7 on 2023-11-21 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Employed',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Middlename',
            field=models.CharField(max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Surname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task.rank', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='Rank',
            field=models.CharField(verbose_name='Должность'),
        ),
    ]
